"""
Sales Engineer Agent
====================
Autonomous agent responsible for closing deals.
It takes Leads, qualifies them, generates outreach, and tracks Sales.
"""

from typing import List
from .semantic_framework import Lead, Sale, db
from .autonomous_tools import AutonomousTools

class SalesEngineer:
    def __init__(self, core_system):
        self.core = core_system
        self.tools = AutonomousTools()
    
    def process_leads(self, leads: List[Lead]):
        """
        Process a batch of leads through the sales funnel.
        """
        print(f"💼 SALES: Processing {len(leads)} leads...")
        
        for lead in leads:
            self.qualify(lead)
            if lead.score >= 70:
                self.engage(lead)
        
    def qualify(self, lead: Lead):
        """
        Qualify a lead based on available data.
        """
        if not lead.organization or not lead.person:
            lead.status = "Disqualified"
            lead.score = 0
            return

        # Simple heuristic qualification
        score = 50 # Base score
        
        # Industry match
        target_industries = ["SaaS", "AI", "B2B", "Technology"]
        if any(ind.lower() in lead.organization.industry.lower() for ind in target_industries):
            score += 20
        
        # Role match
        target_roles = ["CTO", "CEO", "Founder", "VP", "Director"]
        if any(role.lower() in lead.person.role.lower() for role in target_roles):
            score += 20
            
        lead.score = score
        if score >= 70:
            lead.status = "Qualified"
        else:
            lead.status = "Low Priority"
            
        print(f"   [Qualify] {lead.person.name} @ {lead.organization.name}: Score {score} ({lead.status})")
        db.save(lead)

    def engage(self, lead: Lead):
        """
        Generate and send (simulate) outreach.
        """
        print(f"   [Engage] Generating outreach for {lead.person.name}...")
        
        # Generate email content using LLM
        prompt = f"""
        Write a cold outreach email to {lead.person.name}, {lead.person.role} at {lead.organization.name}.
        We are 'Echo', an autonomous business scaling system.
        Value prop: We build agents that automate their growth.
        Tone: Professional, intriguing, concise.
        """
        
        email_body = "Mock email content generated by heuristics."
        if self.core.llm_engine:
            try:
                email_body = self.core.llm_engine.generate_response(prompt)
            except:
                pass
        
        # Create a Sale object to track this opportunity
        sale = Sale(
            lead_id=lead.id,
            amount=5000.0, # Target deal size
            stage="Outreach Sent",
            probability=0.1
        )
        db.save(sale)
        
        # LOGGING AND ACTUAL SENDING
        print(f"   📧 [LIVE ACTION] Sending email to {lead.person.email or 'unknown'}...")
        
        try:
            from .integrations import IntegrationFactory
            sendgrid = IntegrationFactory.get_sendgrid_service()
            
            # Send real email if address exists
            if lead.person.email and "@" in lead.person.email:
                subject = f" Partnership Opportunity: {lead.organization.name} + Echo"
                success = sendgrid.send_email_direct(
                    to_email=lead.person.email,
                    subject=subject,
                    html_content=email_body,
                    from_name="Echo Autonomous System"
                )
                if success:
                    print(f"   ✅ EMAIL SENT successfully to {lead.person.email}")
                else:
                    print(f"   ❌ EMAIL FAILED to send to {lead.person.email}")
            else:
                print("   ⚠️ SKIPPED: No valid email address found.")
                
        except Exception as e:
             print(f"   ❌ EMAIL SYSTEM ERROR: {e}")
             # We proceed anyway to update status for simulation if API fails/missing
        
        lead.status = "Contacted"
        db.save(lead)
