import blank_business_builder.database
"""add outreach tables for bland apollo slack

Revision ID: 1b1187eb0477
Revises: 5b5447971311
Create Date: 2026-04-28 08:16:48.331879

Copyright (c) 2025 Joshua Hendricks Cole (DBA: Corporation of Light). All Rights Reserved. PATENT PENDING.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b1187eb0477'
down_revision = '5b5447971311'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_routes',
    sa.Column('id', blank_business_builder.database.UUIDType(), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('slack_channel_id', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_routes_department'), 'department_routes', ['department'], unique=True)
    op.create_index(op.f('ix_department_routes_is_active'), 'department_routes', ['is_active'], unique=False)
    op.create_table('provider_events',
    sa.Column('id', blank_business_builder.database.UUIDType(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('payload', blank_business_builder.database.JSONType(astext_type=sa.Text()), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_events_event_type'), 'provider_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_provider_events_external_id'), 'provider_events', ['external_id'], unique=False)
    op.create_index(op.f('ix_provider_events_processed'), 'provider_events', ['processed'], unique=False)
    op.create_index(op.f('ix_provider_events_provider'), 'provider_events', ['provider'], unique=False)
    op.create_index(op.f('ix_provider_events_received_at'), 'provider_events', ['received_at'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('id', blank_business_builder.database.UUIDType(), nullable=False),
    sa.Column('user_id', blank_business_builder.database.UUIDType(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transaction_metadata', blank_business_builder.database.JSONType(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_stripe_payment_intent_id'), 'payment_transactions', ['stripe_payment_intent_id'], unique=True)
    op.create_index(op.f('ix_payment_transactions_user_id'), 'payment_transactions', ['user_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', blank_business_builder.database.UUIDType(), nullable=False),
    sa.Column('business_id', blank_business_builder.database.UUIDType(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('outreach_priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_business_id'), 'leads', ['business_id'], unique=False)
    op.create_index(op.f('ix_leads_created_at'), 'leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_leads_department'), 'leads', ['department'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_external_id'), 'leads', ['external_id'], unique=False)
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('lead_enrichments',
    sa.Column('id', blank_business_builder.database.UUIDType(), nullable=False),
    sa.Column('lead_id', blank_business_builder.database.UUIDType(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('payload', blank_business_builder.database.JSONType(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_enrichments_created_at'), 'lead_enrichments', ['created_at'], unique=False)
    op.create_index(op.f('ix_lead_enrichments_lead_id'), 'lead_enrichments', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_enrichments_provider'), 'lead_enrichments', ['provider'], unique=False)
    op.create_table('outreach_attempts',
    sa.Column('id', blank_business_builder.database.UUIDType(), nullable=False),
    sa.Column('lead_id', blank_business_builder.database.UUIDType(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('task', sa.Text(), nullable=True),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('next_action', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_attempts_created_at'), 'outreach_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_outreach_attempts_lead_id'), 'outreach_attempts', ['lead_id'], unique=False)
    op.create_index(op.f('ix_outreach_attempts_scheduled_for'), 'outreach_attempts', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_outreach_attempts_status'), 'outreach_attempts', ['status'], unique=False)
    op.create_table('call_sessions',
    sa.Column('id', blank_business_builder.database.UUIDType(), nullable=False),
    sa.Column('outreach_attempt_id', blank_business_builder.database.UUIDType(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_call_id', sa.String(length=255), nullable=False),
    sa.Column('direction', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=255), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('raw_payload', blank_business_builder.database.JSONType(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['outreach_attempt_id'], ['outreach_attempts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_sessions_created_at'), 'call_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_call_sessions_outreach_attempt_id'), 'call_sessions', ['outreach_attempt_id'], unique=False)
    op.create_index(op.f('ix_call_sessions_provider'), 'call_sessions', ['provider'], unique=False)
    op.create_index(op.f('ix_call_sessions_provider_call_id'), 'call_sessions', ['provider_call_id'], unique=True)
    op.create_index(op.f('ix_call_sessions_status'), 'call_sessions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_sessions_status'), table_name='call_sessions')
    op.drop_index(op.f('ix_call_sessions_provider_call_id'), table_name='call_sessions')
    op.drop_index(op.f('ix_call_sessions_provider'), table_name='call_sessions')
    op.drop_index(op.f('ix_call_sessions_outreach_attempt_id'), table_name='call_sessions')
    op.drop_index(op.f('ix_call_sessions_created_at'), table_name='call_sessions')
    op.drop_table('call_sessions')
    op.drop_index(op.f('ix_outreach_attempts_status'), table_name='outreach_attempts')
    op.drop_index(op.f('ix_outreach_attempts_scheduled_for'), table_name='outreach_attempts')
    op.drop_index(op.f('ix_outreach_attempts_lead_id'), table_name='outreach_attempts')
    op.drop_index(op.f('ix_outreach_attempts_created_at'), table_name='outreach_attempts')
    op.drop_table('outreach_attempts')
    op.drop_index(op.f('ix_lead_enrichments_provider'), table_name='lead_enrichments')
    op.drop_index(op.f('ix_lead_enrichments_lead_id'), table_name='lead_enrichments')
    op.drop_index(op.f('ix_lead_enrichments_created_at'), table_name='lead_enrichments')
    op.drop_table('lead_enrichments')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    op.drop_index(op.f('ix_leads_external_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_department'), table_name='leads')
    op.drop_index(op.f('ix_leads_created_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_business_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_payment_transactions_user_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_stripe_payment_intent_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_provider_events_received_at'), table_name='provider_events')
    op.drop_index(op.f('ix_provider_events_provider'), table_name='provider_events')
    op.drop_index(op.f('ix_provider_events_processed'), table_name='provider_events')
    op.drop_index(op.f('ix_provider_events_external_id'), table_name='provider_events')
    op.drop_index(op.f('ix_provider_events_event_type'), table_name='provider_events')
    op.drop_table('provider_events')
    op.drop_index(op.f('ix_department_routes_is_active'), table_name='department_routes')
    op.drop_index(op.f('ix_department_routes_department'), table_name='department_routes')
    op.drop_table('department_routes')
    # ### end Alembic commands ###
