import blank_business_builder.database
"""Initial schema - all BBB tables

Revision ID: 5b5447971311
Revises:
Create Date: 2026-04-10 06:51:52.628865

Copyright (c) 2025 Joshua Hendricks Cole (DBA: Corporation of Light). All Rights Reserved. PATENT PENDING.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b5447971311'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', blank_business_builder.database.UUIDType(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('subscription_tier', sa.String(length=50), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('license_status', sa.String(length=50), nullable=True),
    sa.Column('license_terms_version', sa.String(length=20), nullable=True),
    sa.Column('license_agreed_at', sa.DateTime(), nullable=True),
    sa.Column('trial_expires_at', sa.DateTime(), nullable=True),
    sa.Column('revenue_share_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=True)
    op.create_table('api_integrations',
    sa.Column('id', blank_business_builder.database.UUIDType(), nullable=False),
    sa.Column('user_id', blank_business_builder.database.UUIDType(), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('config', blank_business_builder.database.JSONType(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_integrations_user_id'), 'api_integrations', ['user_id'], unique=False)
    op.create_table('businesses',
    sa.Column('id', blank_business_builder.database.UUIDType(), nullable=False),
    sa.Column('user_id', blank_business_builder.database.UUIDType(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('business_concept', sa.String(length=500), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_customers', sa.Integer(), nullable=True),
    sa.Column('total_leads', sa.Integer(), nullable=True),
    sa.Column('conversion_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_user_id'), 'businesses', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', blank_business_builder.database.UUIDType(), nullable=False),
    sa.Column('user_id', blank_business_builder.database.UUIDType(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('plan_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('agent_tasks',
    sa.Column('id', blank_business_builder.database.UUIDType(), nullable=False),
    sa.Column('business_id', blank_business_builder.database.UUIDType(), nullable=False),
    sa.Column('agent_role', sa.String(length=50), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('result', blank_business_builder.database.JSONType(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_tasks_business_id'), 'agent_tasks', ['business_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_status'), 'agent_tasks', ['status'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', blank_business_builder.database.UUIDType(), nullable=False),
    sa.Column('user_id', blank_business_builder.database.UUIDType(), nullable=True),
    sa.Column('business_id', blank_business_builder.database.UUIDType(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('details', blank_business_builder.database.JSONType(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', blank_business_builder.database.INETType(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('business_plans',
    sa.Column('id', blank_business_builder.database.UUIDType(), nullable=False),
    sa.Column('business_id', blank_business_builder.database.UUIDType(), nullable=False),
    sa.Column('plan_name', sa.String(length=255), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('market_analysis', sa.Text(), nullable=True),
    sa.Column('financial_projections', blank_business_builder.database.JSONType(astext_type=sa.Text()), nullable=True),
    sa.Column('marketing_strategy', sa.Text(), nullable=True),
    sa.Column('operations_plan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_plans_business_id'), 'business_plans', ['business_id'], unique=False)
    op.create_table('marketing_campaigns',
    sa.Column('id', blank_business_builder.database.UUIDType(), nullable=False),
    sa.Column('business_id', blank_business_builder.database.UUIDType(), nullable=False),
    sa.Column('campaign_name', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('campaign_type', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('performance_metrics', blank_business_builder.database.JSONType(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketing_campaigns_business_id'), 'marketing_campaigns', ['business_id'], unique=False)
    op.create_table('metrics_history',
    sa.Column('id', blank_business_builder.database.UUIDType(), nullable=False),
    sa.Column('business_id', blank_business_builder.database.UUIDType(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('customers', sa.Integer(), nullable=True),
    sa.Column('leads', sa.Integer(), nullable=True),
    sa.Column('conversion_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tasks_completed', sa.Integer(), nullable=True),
    sa.Column('tasks_pending', sa.Integer(), nullable=True),
    sa.Column('tasks_failed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_history_timestamp'), 'metrics_history', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_history_timestamp'), table_name='metrics_history')
    op.drop_table('metrics_history')
    op.drop_index(op.f('ix_marketing_campaigns_business_id'), table_name='marketing_campaigns')
    op.drop_table('marketing_campaigns')
    op.drop_index(op.f('ix_business_plans_business_id'), table_name='business_plans')
    op.drop_table('business_plans')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_agent_tasks_status'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_business_id'), table_name='agent_tasks')
    op.drop_table('agent_tasks')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_businesses_user_id'), table_name='businesses')
    op.drop_table('businesses')
    op.drop_index(op.f('ix_api_integrations_user_id'), table_name='api_integrations')
    op.drop_table('api_integrations')
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
